; This file is project specific and should be checked in to source control.

[mdk]
; This is a shared (mixin) project consumed by both Goose and Crane.
type=mixin

; Toggle trace (on|off) (verbose output)
trace=on

; A list of files and folder to ignore when creating the script.
ignores=obj/**/*,MDK/**/*,**/*.debug.cs

; A list of allowed namespaces.
namespaces=IngameScript
